name: smoke
on: [push, pull_request]
jobs:
  import-check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.11'
      - name: Minimal deps
        run: |
          python -m pip install --upgrade pip
          pip install numpy
      - name: Sanity check README present
        run: test -f README.md
